#!/bin/sh

#/etc/init.d/sys_init start
set `cat /proc/cmdline`
if test -z $IPADDR ; then
#echo "IPADDR must be set run with exec -c \"RUNART=1 IPADDR=<ipaddress>\" "
IPADDR=192.168.10.87
fi
/etc/init.d/network start 2 eth0@eth1
telnetd
brctl addbr br0 
brctl addif br0 eth0
brctl addif br0 eth1
brctl setfd br0 0
ifconfig eth0 up
ifconfig eth1 up
ifconfig br0 $IPADDR up
echo "Set ipaddress to $IPADDR"
insmod /usr/bin/art.ko
sleep 2
echo "Starting ART client 0"
/usr/bin/art_client -console&
echo "Starting ART client 1"
/usr/bin/art_client -console  -instance 1&
arping -Ub -c 2 -I br0 $IPADDR&

