#!/bin/sh
rkscli_cmd="/usr/bin/rkscli"

echo "Set Simulator Environment"
echo "-->Start codump_client"
/usr/sbin/codump_client -m `cat /proc/v54bsp/MACbase` &
echo "-->Start telnetd"
/usr/sbin/telnetd -l /bin/sh &

echo "-->set AP ignore FW version to avoid SCG upgrade"
apmgr_ignore_ver=`$rkscli_cmd -c "get rpmkey wsgclient/ignore-fw t"`
if [ -z "$apmgr_ignore_ver" ]; then
    $rkscli_cmd -c "set rpmkey wsgclient/ignore-fw t"
    echo "--->RPM: set rpmkey wsgclient/ignore-fw t !!"
fi

ifconfig eth0 down
