#!/bin/sh
rkscli_cmd="/usr/bin/rkscli"

echo "Set Simulator Environment"
echo "-->Start codump_client"
/usr/sbin/codump_client -m `cat /proc/v54bsp/MACbase` &
echo "-->Start telnetd"
/usr/sbin/telnetd -l /bin/sh &

echo "-->set APMGR ignore version to avoid ZD upgrade"
apmgr_ignore_ver=`$rkscli_cmd -c "get rpmkey apmgr-ignore-ver"`
if [ -z "$apmgr_ignore_ver" ]; then
    $rkscli_cmd -c "set rpmkey apmgr-ignore-ver t"
    echo "--->RPM: set rpmkey apmgr-ignore-ver t !!"
fi

ifconfig eth0 down
