#!/bin/sh

iwconfig wlan0 essid "Ruckus"
iwconfig wlan0 channel 11
brctl addbr br0
brctl addif br0 eth0
brctl addif br0 eth1
brctl addif br0 wlan0
ifconfig eth0 up
ifconfig eth1 up
ifconfig br0 192.168.0.1 netmask 255.255.255.0

