#!/bin/sh
_sys_start()
{
#mount -o remount,rw /
#mount -a
mount -t proc /proc /proc
mount -t tmpfs -o defaults,size=4M tmpfs /tmp

if [ ${_init_} -gt 1 ] ; then
#
# mount datafs
data_num=99
_grep_datafs()
{
    while read pn sz esz name ; do
        case "${name}" in
        '"datafs"')  data_num=${pn#mtd}
             data_num=${data_num%:}
             break ;;
        *) ;;
        esac
    done < /proc/mtd
}
_grep_datafs
if [ ${data_num} -lt 20 ]; then
    mount -t jffs2 /dev/mtdblock${data_num} /writable
	if [ ! -d /writable/etc ]; then
		mkdir /writable/etc
	fi
else
    echo "*** Cannot find datafs partition" >&2
fi
#

#
# fix links for /var
vardirs="run log spool lock ftp"
for d in ${vardirs} ;do
#	rm -f  /var/${d}
	mkdir -p /tmp/var/${d}
# symlink for these are already in target_skeleton
#	ln -fs /tmp/var/${d} /var/${d}
done

#init -gt 1
fi

mount -o remount,ro /
mount
}

_sys_stop()
{
	mount -o remount,rw /
}


if [ "$INIT" != "" ] ; then
    _init_=${INIT}
else
    _init_=3
fi
case "$1" in
start|"")
	_sys_start ;;
stop)
	_sys_stop ;;
*)	;;
esac
