#!/bin/sh

#/etc/init.d/sys_init start
set `cat /proc/cmdline`
if test -z $IPADDR ; then
#echo "IPADDR must be set run with exec -c \"RUNART=1 IPADDR=<ipaddress>\" "
IPADDR=10.0.0.1
fi
/etc/init.d/network start 1
telnetd
ifconfig eth0 $IPADDR up
echo "Set ipaddress to $IPADDR"
arping -Ub -c 2 -I eth0 $IPADDR
insmod /usr/bin/art.ko
art_client 
