#!/bin/sh

#/etc/init.d/sys_init start
set `cat /proc/cmdline`
if test -z $IPADDR ; then
IPADDR=192.168.10.88
fi
/etc/init.d/network start 1
telnetd
ifconfig eth0 $IPADDR up
echo "Set ipaddress to $IPADDR"
arping -Ub -c 2 -I eth0 $IPADDR
insmod /usr/bin/art.ko
art_client

